### ISSUE TITLE
Roadmap : GOTO Next

### ISSUE THREAD

**Issue by v3ss0n** [v3ss0n/goto#54]
After we fixed Outstanding problems , i am planning to do some cool features:

- [ ] Disk based indexes
- [ ] Grouping : Grouping of symbols based on grammer type.
- [ ] Symbol Zen : Focus mode that swoop directly to the area of symbol and code there, hiding (or auto folding ) all other parts 
- [ ] Symbols Crumb : When enabled , a Breadcrumb Navigation will be added below the tab bar . Using it we can navigate Symbols within current file. Also when we move focus to a particular symbol , navigation will be updated to show where we are.
